x-web-variables: &web-variables
  DEBUG: dev
  ALLOWED_HOSTS: http://localhost
  HOST: http://localhost:8000/'
  POSTGRES_DB:
  POSTGRES_USER:
  POSTGRES_PASSWORD:
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    environment: *web-variables
    ports:
      - 8000:8080