x-web-variables: &web-variables
  DEBUG: dev
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    environment: *web-variables
    ports:
      - 8000:8080