x-web-variables: &web-variables
  TELEGRAM_BOT_TOKEN_KEY: 7546803808:AAEdPITUtJQrwTGwRFvQRHTwmoD7BDn-LpY
  API_TOKEN: ''
  API_URL: ''
  API_BASE_PATH: ''
  API_VERSION: ''
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    environment: *web-variables
    ports:
      - 8000:8080