services:
  db:
    image: "postgres:15-alpine"
    restart: unless-stopped
    volumes:
      - ./.docker/postgresql/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: imei_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: strongpassword
      TZ: 'GMT+3'
      PGTZ: 'GMT+3'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d imei_db -U admin"]
      interval: 1s
      timeout: 3s
      retries: 5