# Generated by Django 5.1.5 on 2025-02-04 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('imei', models.CharField(max_length=15)),
                ('est_purchase_date', models.IntegerField()),
                ('sim_lock', models.BooleanField()),
                ('warranty_status', models.CharField(max_length=100)),
                ('repair_coverage', models.CharField(max_length=100)),
                ('technical_support', models.CharField(max_length=100)),
                ('model_desc', models.CharField(max_length=100)),
                ('demo_unit', models.BooleanField()),
                ('refurbished', models.BooleanField()),
                ('purchase_country', models.CharField(max_length=100)),
                ('apple_region', models.CharField(max_length=100)),
                ('fmi_on', models.BooleanField()),
                ('lost_mode', models.CharField(max_length=100)),
                ('usa_block_status', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IMEICheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('web', 'web'), ('api', 'api')], max_length=50)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('processing', 'processing'), ('successful', 'successful'), ('unsuccessful', 'unsuccessful'), ('failed', 'failed')], max_length=50)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=15)),
                ('processed_at', models.IntegerField()),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='CheckIMEI.property')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='CheckIMEI.service')),
            ],
        ),
    ]
