x-api-variables: &api-variables
  SERVER_HOST: ''
  API_BASE_PATH: ''
  API_VERSION: ''
  API_URL_TAKE_TOKEN: ''
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment: *api-variables
    ports:
      - 8080:8080